version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: exxdx
      POSTGRES_USER: exxdx
      POSTGRES_PASSWORD: exxdxpw
    ports: ['5432:5432']
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata: